# Generated by Django 4.2.7 on 2024-01-15 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField()),
                ('food_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='menu.foodmenu')),
            ],
        ),
    ]
