# Generated by Django 4.2.7 on 2024-01-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('menu', '0002_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodmenu',
            name='category',
        ),
        migrations.AddField(
            model_name='foodmenu',
            name='category',
            field=models.ManyToManyField(to='category.category'),
        ),
    ]
