# Generated by Django 4.2.7 on 2024-01-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderhistry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='orderhistry',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
