# Generated by Django 5.0 on 2024-01-17 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_total_cost_alter_orderhistry_total_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='food_item',
            new_name='food_items',
        ),
        migrations.RenameField(
            model_name='orderhistry',
            old_name='food_item',
            new_name='food_items',
        ),
    ]
